-- Initial schema for a new LockerOps database.
-- Existing databases are baselined at version 1 because their schema was
-- reviewed and validated before Flyway was introduced.

CREATE TABLE public.locker_stations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_url VARCHAR(500),
    location VARCHAR(150) NOT NULL,
    manufacturer VARCHAR(100) NOT NULL,
    model VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    status VARCHAR(30) NOT NULL,
    CONSTRAINT locker_stations_status_check
        CHECK (status IN ('ACTIVE', 'INACTIVE', 'MAINTENANCE', 'OUT_OF_SERVICE'))
);

CREATE TABLE public.locker_compartments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compartment_number INTEGER NOT NULL,
    size VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    locker_station_id BIGINT NOT NULL,
    CONSTRAINT locker_compartments_size_check
        CHECK (size IN ('SMALL', 'MEDIUM', 'LARGE', 'EXTRA_LARGE')),
    CONSTRAINT locker_compartments_status_check
        CHECK (status IN ('AVAILABLE', 'RESERVED', 'OCCUPIED', 'OUT_OF_SERVICE')),
    CONSTRAINT fkoay7oovrkhhq807wuc5oqkcav
        FOREIGN KEY (locker_station_id) REFERENCES public.locker_stations(id)
);

CREATE TABLE public.reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cancelled_at TIMESTAMP(6) WITH TIME ZONE,
    completed_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    customer_reference VARCHAR(100),
    expired_at TIMESTAMP(6) WITH TIME ZONE,
    reservation_reference UUID NOT NULL,
    reserved_from TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    reserved_until TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    status VARCHAR(30) NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    locker_compartment_id BIGINT NOT NULL,
    CONSTRAINT reservations_status_check
        CHECK (status IN ('PENDING_PAYMENT', 'CONFIRMED', 'CANCELLED', 'EXPIRED', 'COMPLETED')),
    CONSTRAINT uk1gxgu0tbv105cnkbmp6bm7nhe UNIQUE (reservation_reference),
    CONSTRAINT fkff5a1xlfmhqnc7thkquj7ltt3
        FOREIGN KEY (locker_compartment_id) REFERENCES public.locker_compartments(id)
);

CREATE TABLE public.tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cancelled_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    expired_at TIMESTAMP(6) WITH TIME ZONE,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    issued_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    status VARCHAR(30) NOT NULL,
    ticket_code VARCHAR(30) NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    reservation_id BIGINT NOT NULL,
    CONSTRAINT tickets_status_check
        CHECK (status IN ('ISSUED', 'CANCELLED', 'EXPIRED', 'COMPLETED')),
    CONSTRAINT uk_tickets_reservation_id UNIQUE (reservation_id),
    CONSTRAINT uk_tickets_ticket_code UNIQUE (ticket_code),
    CONSTRAINT fktefrntjvcsu43l1fjmybtqqmx
        FOREIGN KEY (reservation_id) REFERENCES public.reservations(id)
);

CREATE TABLE public.access_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_hash VARCHAR(100) NOT NULL,
    code_preview VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    first_used_at TIMESTAMP(6) WITH TIME ZONE,
    last_used_at TIMESTAMP(6) WITH TIME ZONE,
    revoked_at TIMESTAMP(6) WITH TIME ZONE,
    status VARCHAR(30) NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    use_count INTEGER NOT NULL,
    valid_from TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    ticket_id BIGINT NOT NULL,
    CONSTRAINT access_codes_status_check
        CHECK (status IN ('ACTIVE', 'EXPIRED', 'REVOKED')),
    CONSTRAINT uk_access_codes_code_hash UNIQUE (code_hash),
    CONSTRAINT fkry8crbue3p81lye6v4ct4wb0p
        FOREIGN KEY (ticket_id) REFERENCES public.tickets(id)
);

CREATE INDEX idx_access_codes_ticket_id
    ON public.access_codes USING btree (ticket_id);
CREATE INDEX idx_access_codes_ticket_id_status
    ON public.access_codes USING btree (ticket_id, status);
CREATE INDEX idx_tickets_status
    ON public.tickets USING btree (status);
