-- Adds the payment quote to reservations and records simulated payment attempts.
-- Existing reservations are retained with a zero-value historical quote.

ALTER TABLE public.reservations
    ADD COLUMN amount_minor BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN currency VARCHAR(3) NOT NULL DEFAULT 'EUR',
    ADD COLUMN payment_expires_at TIMESTAMP(6) WITH TIME ZONE;

ALTER TABLE public.reservations
    ADD CONSTRAINT reservations_amount_minor_check CHECK (amount_minor >= 0);

ALTER TABLE public.reservations
    ALTER COLUMN amount_minor DROP DEFAULT,
    ALTER COLUMN currency DROP DEFAULT;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM public.locker_compartments
        GROUP BY locker_station_id, compartment_number
        HAVING count(*) > 1
    ) THEN
        RAISE EXCEPTION 'Duplicate compartment numbers exist within the same locker station';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM public.reservations
        WHERE status IN ('PENDING_PAYMENT', 'CONFIRMED')
        GROUP BY locker_compartment_id
        HAVING count(*) > 1
    ) THEN
        RAISE EXCEPTION 'Multiple active reservations exist for the same locker compartment';
    END IF;
END
$$;

ALTER TABLE public.locker_compartments
    ADD CONSTRAINT uk_locker_compartments_station_number
        UNIQUE (locker_station_id, compartment_number);

CREATE UNIQUE INDEX uk_reservations_active_compartment
    ON public.reservations (locker_compartment_id)
    WHERE status IN ('PENDING_PAYMENT', 'CONFIRMED');

CREATE INDEX idx_reservations_pending_payment_expiration
    ON public.reservations (payment_expires_at)
    WHERE status = 'PENDING_PAYMENT';

CREATE TABLE public.payment_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_reference UUID NOT NULL,
    reservation_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL,
    amount_minor BIGINT NOT NULL,
    currency VARCHAR(3) NOT NULL,
    processed_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT payment_attempts_status_check
        CHECK (status IN ('APPROVED', 'DECLINED')),
    CONSTRAINT payment_attempts_amount_minor_check
        CHECK (amount_minor > 0),
    CONSTRAINT uk_payment_attempts_reference UNIQUE (payment_reference),
    CONSTRAINT fk_payment_attempts_reservation
        FOREIGN KEY (reservation_id) REFERENCES public.reservations(id)
);

CREATE INDEX idx_payment_attempts_reservation_id
    ON public.payment_attempts (reservation_id);
